version: "3"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    restart: always
    depends_on:
      - db

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: front/Dockerfile
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - db

  script:
    build:
      context: .
      dockerfile: script/Dockerfile
    restart: always
    depends_on:
      - db

